# Generated by Django 4.1.7 on 2023-03-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ipmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpModel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
