# Generated by Django 4.1.7 on 2023-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='images/news/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
