# Generated by Django 4.1.7 on 2023-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ipmodel_post_likes_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
