# Generated by Django 4.1.7 on 2023-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_image_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='images/news/%Y/%m/%d', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
