# Generated by Django 3.2.8 on 2023-03-26 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpLikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
