# Generated by Django 4.1.7 on 2023-03-21 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_likedislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnumber', models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков')),
                ('likedone', models.ManyToManyField(related_name='users_video_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
