# Generated by Django 4.1.7 on 2023-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tag_remove_post_tags_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
    ]
