# Generated by Django 4.1.7 on 2023-03-22 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_remove_likes_likes_remove_video_likedone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Лайки', to=settings.AUTH_USER_MODEL),
        ),
    ]
